### ISSUE TITLE
Image colour slightly changes when loaded as Object3D

### ISSUE THREAD

**Issue by John2397** [jscastro76/threebox#136]
Hello @jscastro76,

I noticed that when I load an image on the map as an `Object3D` with `Threebox`, the picture color slightly lightens. However the color is correct when I load it with `Threejs` by adding the `Object3D` to the `scene`  or when I load it with `Mapbox` only

[This fiddle](https://jsfiddle.net/oda9nkc8/) loads the image with Threebox (color is lightened) and Mapbox (color is correct)
(^Threebox library must be included to work)

[This fiddle](https://jsfiddle.net/bp8ug52z/1/) loads the image with Threejs only   (color is correct)

This is the result for each one of them
![geometry](https://user-images.githubusercontent.com/52736731/101338888-49364a80-3886-11eb-8c5e-e8fe2316fefd.png)

My question is why is the color changed when I load the image as an `Object3d` with `Threebox` (left upper photo)? Is there any way to prevent this?

**Comment by jscastro76** [comment]
Hummm... something to investigate. So far, I have not added yet any image in that way to my maps, but the version of three embedded in Threebox is 117 and your sample with three is 123

**Comment by John2397** [comment]
Thank you for the response.

I've added to my three js demo the same lights as I have on my threebox demo to check if I can get the wrong colored pictrure to appear, but nothing changes. The picture in three js demo is still correctly displayed

**Comment by jscastro76** [comment]
I got it... 
![image](https://user-images.githubusercontent.com/38470852/101381115-a5b15e00-38b6-11eb-9877-e0a59e2e8198.png)

the issue is that in threbox `WebGLRenderer` is initialized with `this.renderer.outputEncoding = THREE.sRGBEncoding;`. This is required for most of the 3D objects that I use, loading complex textures and materials map-based that require this configuration, so by design I decided to set this attribute by default.
Anyway you can modify this behavior in your code easily just adding this line below the `window.tb` initialization:
```js		
window.tb = new Threebox(
	map,
	map.getCanvas().getContext('webgl'),
	{
		defaultLights: true,
		enableSelectingFeatures: true, //change this to false to disable fill-extrusion features selection
		enableSelectingObjects: true, //change this to false to disable 3D objects selection
		enableDraggingObjects: true, //change this to false to disable 3D objects drag & move once selected
		enableRotatingObjects: true, //change this to false to disable 3D objects rotation once selected
	}
);
tb.renderer.outputEncoding = THREE.LinearEncoding;
```
One more thing, I recommend you to create the custom layer after the raster one, this will ensure Threebox can maintain the depth calculation properly if you add other 3D objects... Otherwise you'll have issues like this below when adding 3D objects apart from the Plane geometry
![image](https://user-images.githubusercontent.com/38470852/101383064-f7f37e80-38b8-11eb-852c-c31c252c4786.png)

**Comment by John2397** [comment]
Thank you, once again : )

**Comment by jscastro76** [comment]
My pleasure to help @John2397
