### ISSUE TITLE
How can I set model opacity transition with zoom range

### ISSUE THREAD

**Issue by codingBingo0309** [jscastro76/threebox#153]
When I setZoomRange to custom layer, what can I do for model opacity transition with gardient

**Comment by jscastro76** [comment]
Currently `tb.setLayerZoomRange’ for custom layers doesn’t support an opacity transition between zoom  ranges as opacity is not supported by mapbox on CustomLayerInterface. It could be a good new feature to implement

**Comment by libertyfree** [comment]
Do you plane to solve this question,have verison plane? I alse want  this feature.

**Comment by jscastro76** [comment]
Hi @libertyfree @codingBingo0309, Are you both the same person or you work in the same project??
I receive the same issues and comments from you both with screenshots of the same building and wheelchairs. I'd appreciate clarity, I prefer to know who I'm talking to.

This could be a good addition to Threebox, but it's super-specific visual behavior, not a bug, and not so easy to solve because opacity is not supported by Mapbox on custom layers, so it must be made object by object. 
Due to this, for me the priority is low to implement this feature.

**Comment by codingBingo0309** [comment]
Sorry, we are not the same person. I just use his picture for my question.
And I know this question is not important, because it's just like an optimization, not a bug.
So can you give me any suggestion for this question, or how to solve, thanks!

**Comment by jscastro76** [comment]
I haven’t started the research on this topic yet. Opacity transitions are part of the Paint attribute of the layers, but it’s not implemented in CustomLayerInterface. That’s the point I would start from.

**Comment by codingBingo0309** [comment]
Thanks, and it's also my research on the topic.

**Comment by jscastro76** [comment]
@codingBingo0309 have you coded anything on this topic?

**Comment by codingBingo0309** [comment]
Sorry, I'm too busy to work others.

**Comment by jscastro76** [comment]
Ok, closing the question then
