### ISSUE TITLE
Misplaced elements when the map has a different fov

### ISSUE THREAD

**Issue by KarimJedda** [jscastro76/threebox#154]
Hi jscastro76, 

thanks for this great library, it's been very helpful so far. 

While using the extrude example in the examples folder, I changed the map FOV:

map.transform._fov = 0.2;

which resulted in the elements flying around on the map and not staying at their positions. Am I doing something wrong? Let me know if you have an idea or where I can assist you with a PR. Thanks,

**Comment by jscastro76** [comment]
Hi @KarimJedda, thanks for your interest in Threebox.
I guess you’re trying to get an orthographic perspective which is some kind of a hack in Mapbox, that’s why they keep the transformation fov in a private variable `map.transformation._fov`, indeed Mapbox has a [hardcoded value](https://github.com/mapbox/mapbox-gl-js/blob/f21691c54014bd3d246ff790e4cba5a7e7b33415/src/geo/transform.js#L93) for fov which is `Math.atan(3 / 4)`
That would require to change also the orthographic camera in threejs scene which is now fixed to PerspectiveCamera. 
I did a try while ago on this topic, but it didn’t work very well, specially with fill-extrusions and Threebox 3D objects together and very close or containing each other so that’s why I didn’t add the commit, but I was not sure if was mostly related with the issues in the depth calculations #145 that are now solved.
As a quick check you could change the value of Constants.FOV to 0.2 and the instantiation of PerspectiveCamera by OrthographicCamera in Threebox constructor, it should work as a quick and deity. If you think it works, I would think seriously on including it as a Threebox init param.

**Comment by KarimJedda** [comment]
Hi @jscastro76 thanks for the answer, so far I'm loving Threebox!! I will try it and let you know hopefully shortly.

**Comment by KarimJedda** [comment]
Ok I did not manage to make it work :( but it's okay it will have to wait until I get a bit better at javascript. Thanks anyway and wish you a happy new year in advance.

**Comment by jscastro76** [comment]
> Ok I did not manage to make it work :( but it's okay it will have to wait until I get a bit better at javascript. Thanks anyway and wish you a happy new year in advance.

Hi Karim!
First of all, happy new year for you too!
I’ll take a look to this once back from holidays.

**Comment by jscastro76** [comment]
Hi @KarimJedda 
I managed to create a fully OrthographicCamera view, and looks perfect
![image](https://user-images.githubusercontent.com/38470852/103407969-ea9c7d80-4b60-11eb-9e2c-2ebb41a28f1f.png)

The only issue I found is that it has a collateral effect and breaks the raycasting on the 3D Objects, so if I'm able to solve the raycasting problem, I'll push the changes with this new feature.

**Comment by KarimJedda** [comment]
Wow! This looks absolutely amazing, great job and thanks for spending some time on this. If I can help somehow let me know I'd gladly test and add some documentation if you need.

**Comment by jscastro76** [comment]
Hi @KarimJedda I think you will love this demo 😃 
![Uploading changingFOV.gif…]()

**Comment by KarimJedda** [comment]
Woahhhhh how did you achieve this magic!!!? It looks absolutely gorgeous!

**Comment by jscastro76** [comment]
It took a bit of work and refactoring, but it was thanks to your suggestion why I did it. Anyway this is only changing the FOV, I found Mapbox fill-extrusions cannot go below 2.5 degrees because it starts to calculate wrongly the depth of the buildings. So 2.5 won't ever be pure orthographic, but quite similar. There will be the option to set the FOV by init param in Threebox constructor, and also through a method in runtime.

HOWEVER, I have also added a pure Orthographic view which uses 0.01 degrees in Mapbox, it breaks the fill-extrusions but it's 100% accurate with 3D models as it uses a `THREE.OrthographicCamera` instead of a `THREE.PerspectiveCamera`.

**Comment by jscastro76** [comment]
@KarimJedda ready to download in the new realease v2.1.6, it's in the example [09-raycaster.html](https://github.com/jscastro76/threebox/blob/master/examples/09-raycaster.html)

**Comment by KarimJedda** [comment]
Will try it out tonight and let you know!! :D Thanks!!!!

**Comment by KarimJedda** [comment]
Ok it took a bit longer than expected but... it's beautiful!!
Thanks so much :D 
![FOV](https://user-images.githubusercontent.com/5029053/104763301-f180de00-5765-11eb-8e02-47fc23361e04.PNG)

**Comment by jscastro76** [comment]
Woooooww! Beautiful indeed!
It seems like SIM city 2000! 😀

**Comment by KarimJedda** [comment]
Thank you, yes it has exactly that vibe I was looking for, I'll send you the end result once it's online. I've been side tracked lately with creating my own mbtiles and self hosting the underlying tile server. It's been a ride but at least it works now! Especially I found out that it is also possible to directly generate 3D tiles so that it would be possible to have beautiful and realistic buildings directly on the map. This topic is so exciting!

**Comment by jscastro76** [comment]
Congrats buddy, it looks awesome. 
Glad this plug-in was of help for you. I look forward to see the final result
