### ISSUE TITLE
vertical line

### ISSUE THREAD

**Issue by codingBingo0309** [jscastro76/threebox#186]
Can I draw a vertical line? and also the model can move follow this vertical line?

**Comment by jscastro76** [comment]
Yes, you can. As long as the lines have three dimensions, you only need to use the third coordinate which is altitude.
```js
// set up geometry for a line to be added to map, lofting it up a bit for *style*
let line = {
	"path": [
		[
			-3.45916435,
			40.48319667,
			0
		],
		[
			-3.45916435,
			40.48319667,
			50
		]
	]};

// create and add line object
line = tb.line({
	geometry: line.path,
	width: 5,
	color: 'steelblue'
});

tb.add(line);
```

Any object can be moved vertically, using `obj.set()`
```js 
let c = obj.coordinates;
obj.set({ coords: [c[0], c[1], 50], duration: 2000 })` and the object will take 2 seconds to move 50 meters up.
```

**Comment by codingBingo0309** [comment]
Thanks, I implemented the vertical line, but I used obj.set(), the model can't be moved, and the model just hidden,
so what't wrong with me?
It's my code:
`obj.set({
        coords: [
          path[path - 1], // [120,30,0]
          routelines[0].geometry.coordinates[routelines[0].geometry.coordinates.length - 1].concat(toFloorHeight), // [120, 30, 20]
          toFloorHeight // 20
        ],
        duration: 2000,
      })`

**Comment by jscastro76** [comment]
> Thanks, I implemented the vertical line, but I used obj.set(), the model can't be moved, and the model just hidden,
> so what't wrong with me?
> It's my code:
> `obj.set({ coords: [ path[path - 1], // [120,30,0] routelines[0].geometry.coordinates[routelines[0].geometry.coordinates.length - 1].concat(toFloorHeight), // [120, 30, 20] toFloorHeight // 20 ], duration: 2000, })`

Sorry, but your code is almost impossible to read with comments in the middle of the code instead of new lines, and you also add variables and arrays that I don't know as I have no psych powers. 
Just to make you realize, this what you pasted.
![image](https://user-images.githubusercontent.com/38470852/106104138-5105c300-6142-11eb-93ee-60f4a4950e60.png)
You are not following the example I provided above nor [checking the documentation](https://github.com/jscastro76/threebox/blob/master/docs/Threebox.md#set).

**Again** follow the example, now without variables, it's extremely simple
```js
// if your object is set at [120, 30, 0] before this line
obj.set({ coords: [120, 30, 50], duration: 2000 });  // and the object will take 2 seconds to move 50 meters up.
```
This is an open source project not a support desktop, As a general rule, if a question does not show any minimum effort in making your code easier to read, I might close the issue here and instead recommend asking on Stack Overflow.
