### ISSUE TITLE
Terrain within Three Editor?

### ISSUE THREAD

**Issue by j2l** [jscastro76/threebox#248]
Hello!
First of all thank you for this great fork!
I crawled the documentation and issues here and read some SO before posting.

**Threebox version**:
2.2.3+, downloaded today from master, commit  #243 (Create a new example on terrain layer)

### Question
Ultimately, I'd need to have mapbox terrain tiles withing a THREE Editor.
I simply downloaded the main THREE editor, but maybe there's another solution.

So far, I mixed the [terrain example](https://github.com/jscastro76/threebox/blob/master/examples/21-terrain.html) within the editor index.html and there are no error in the console or server, but since there are now 2 canvases, the model is displayed below the scene.

It's very rough but here's where I am:
![image](https://user-images.githubusercontent.com/65325/118391967-414db400-b637-11eb-9a99-adb80e0e0e00.png)
when viewport canvas is `display:none`, I see the map:
![image](https://user-images.githubusercontent.com/65325/118392279-23814e80-b639-11eb-9d3c-8d261197254c.png)

How could I mix Threebox content within the editor?
Or is there a kind of editor within threebox? I saw gifs on SO where you move the models over the map.
This might be done the other way around: threebox as the main three scene and add editor above it, but I don't know which one is the easiest.

Extra bonus question:
In the end, best would be to get the 3D map from height map and with LOD like ye olde: https://labs.mapbox.com/bites/00332/#15.6896/36.3833/-112.6467/34.2734/36
Do you think heightmap could be used in threebox future for terrains?

Hope it makes sense :)
Thank you

**Comment by jscastro76** [comment]
Hi @j2l 
I love the idea, it seems amazing, but I never tried so... 
Based on what you describe there are 2 scenarios:
- **Integrate Threejs editor**
The good news is that you don't have any console errors, but definitely you'll need to have only one canvas, otherwise it will be impossible to use 3D editor features on top of threebox. Do you have any repo to look at?

- **Build your own editor**
Threebox include built in the option to move and rotate any 3D model just adding `enableSelectingObjects: true`, `enableDraggingObjects: true` and `enableRotatingObjects` to Threebox initiatization params, those are the [described in the documentation](https://github.com/jscastro76/threebox/blob/master/docs/Threebox.md#threebox-instance). Of course you can create your own editor to include and position, I did my own 3D warehouse for my projects with a simple modal window that allows me to select from all the 3D models available in my solution.
![image](https://user-images.githubusercontent.com/38470852/118446232-af55b200-b6ef-11eb-84dc-0cb48d89f104.png)
Obviously this approach takes a bit of extra effort, but nothing very complex as it seems to fully integrate the Threejs editor.

**Comment by j2l** [comment]
Thank you very much @jscastro76 !

Unfortunately, I don't have a repo for this for now.
As I only changed index.html, I attached it to this post.
[index.html.zip](https://github.com/jscastro76/threebox/files/6493007/index.html.zip)
It's based on https://threejs.org/editor/

Threebox enableSelectingObjects enableDraggingObjects and enableRotatingObjects seem great!
I might need more editor stuff though, like equirectangular background, ...

Let's try the first approach, a simple step at a time, without all the editor for now:
Is there a way to integrate threebox within an existing THREE scene?

**Comment by j2l** [comment]
Hello @jscastro76 
Sorry to bump but I'd love to see it work :)
Did you try my file?

**Comment by jscastro76** [comment]
No, sorry for the misunderstanding but I didn’t say I was going to do it. I proposed you 2 potential solutions, conceptually but I’m not going to implement them.
I’m always happy to solve bugs detected and consider new features if they make sense and add value to the project, and what you propose is basically your client UI needs.
But luckily this is an open source project with MIT license, you have rights to modify it for your own purpose keeping the license terms and indeed you’re invited to contribute with a new example once with that if you want.

**Comment by j2l** [comment]
Actually it's for my student game project and I thought it would help others to get ThreeJS Editor and Threebox together.

**Comment by jscastro76** [comment]
> Actually it's for my student game project and I thought it would help others to get ThreeJS Editor and Threebox together.

And it's totally fair @j2l, but it's a client UI specific need and use case, not a need from the plugin point of view. 
As said I'm happy to add your example as contributor if you finally achieve it
