### ISSUE TITLE
No drawing polygon feature?

### ISSUE THREAD

**Issue by spirityy** [jscastro76/threebox#254]
Hi jscastro76,
There is no drawing polygon feature? i found .line,.tube api,but no polygon api.

` const a = generatePolygonFromCoords([cords], new THREE.MeshBasicMaterial({ color: 0xff0000 }));
                        console.info(444, a);
                        tb.add(tb.Object3D({ obj: a }));
`

I drew it through THREE.MESH, inert ThreeBox by Object3d, but I didn't render it to the specified location.

<img width="656" alt="polygon" src="https://user-images.githubusercontent.com/424997/119790645-aee6c380-bf06-11eb-8187-7c776d9dd26f.png">

**Comment by jscastro76** [comment]
With only one line of code it’s quite hard to help you, but your code is lacking of `tb.setCoords` so where are you positioning your polygon?
BTW you can use extrusions (and define a minimum height) to create any polygon.

**Comment by spirityy** [comment]
![image](https://user-images.githubusercontent.com/424997/120154796-cbdf0780-c222-11eb-9fc8-7e09d4a87c20.png)
How can i draw this polygon use threebox?

**Comment by jscastro76** [comment]
Writing the code to make it!

Yes, my answer is as ridiculous as your question. I have no psych powers, without a minimal reproducible example or at least the code used, how do you think I could help?

This is an open source project MIT license, not a support desktop of a licensed product with an SLA. As a general rule, if a question does not use the issue template that you removed explicitly, I might close the issue here
