### ISSUE TITLE
queryRenderedFeatures   question

### ISSUE THREAD

**Issue by ouxiang** [jscastro76/threebox#257]
Use queryRenderedFeatures method when clicked some features. The result is below:
![image](https://user-images.githubusercontent.com/7112672/120743798-431ae100-c52c-11eb-8434-11d03cdc7dff.png),the point coords is not clicked position.What is the reason for this？

**Comment by jscastro76** [comment]
Change your code line 123 and add the attribute `getRigthCoords = true`.

Yes, my answer is as ridiculous as your question. I have no psych powers, without a minimal reproducible example or at least the code used, how do you think I could help?

This is an open source project MIT license, not a support desktop of a licensed product with an SLA. As a general rule, if a question does not use the issue template that you removed explicitly, I might close the issue here
