### ISSUE TITLE
当移除threebox图层实例时报错如下：Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'destroy')

### ISSUE THREAD

**Issue by ycsgis** [jscastro76/threebox#282]
1.执行代码如下：
tb.dispose();
mapboxInstance.remove();
2.报错如下：
![image](https://user-images.githubusercontent.com/28531822/134860348-d547d389-c053-46e6-b2a6-b1cd461e3e9b.png)
因为什么导致整个错误呢

**Comment by jscastro76** [comment]
Sorry, I don't speak chinese. 
That error couldn't come from Threebox, because there's no variable called destroy in any part of the code. 
If you mapboxInstance is the same instance you provide to Threebox, you don't need to call `remove()` because [it's already called by `tb.dispose()`](https://github.com/jscastro76/threebox/blob/d6ca8e83be2a3fb879b039c8cb50bdb6af5430f1/src/Threebox.js#L1100).
