### ISSUE TITLE
When changing the model position using SelectedChange, the checkbox remains in the same position

### ISSUE THREAD

**Issue by Dongsheng-Zhang** [jscastro76/threebox#284]
![20210927164834](https://user-images.githubusercontent.com/22702908/134878301-9a1f9c68-39d8-49f6-816a-52e18ed4ff87.png)

Use SelectedChange and click setCenter to change the original position, the position of the selected box is still the original, is there any way to deal with it, looking forward to your reply

**Comment by jscastro76** [comment]
This is weird, I move all my objects with drag & drop and the box is always stuck to the object (because model and bos are grouped) [![enter image description here][3]][3]

  [3]: https://i.stack.imgur.com/BNmka.gif

What code are you using to move the object?

**Comment by Dongsheng-Zhang** [comment]
`obj.setCenter({
        x: 0,
        y: 0,
        z: height
 });`
I change the position of the model by changing setCenter, and what I need is a click to change the position once

**Comment by jscastro76** [comment]
That is not changing the position, that's changing the anchor center, that's why yor're displacing the object away from its bounding box.
To move an object you can use [`obj.setCoords`](https://github.com/jscastro76/threebox/blob/master/docs/Threebox.md#setcoords) or [`obj.set`](https://github.com/jscastro76/threebox/blob/master/docs/Threebox.md#set), both of them admit an array of 3 positions por x, y, z. 
If what you want to do is to apply a relative movement to the current position, you can use `obj.set` with the option `translation` and no duration
