### ISSUE TITLE
tb.dispose does not fully dispose of all components

### ISSUE THREAD

**Issue by Philip2809** [jscastro76/threebox#299]
Hi! I am making an mapbox map in angular with threebox to manage the 3d models. I am wondering how to properly dispose of the 3d map so it can be reinitialized. We have both an 3d and a 2d map (leaflet) and you should be able to switch between them. Right now we use `ngIf` to switch between the maps, both of them are separate components.

**Describe the bug**
When reinitiating the map after using tb.dispose() I get a lot of errors in the console: "TypeError: this.renderer.render is not a function" However the map the the functions of theebox work as expected.

**Expected behavior**
Errors should not happen

**Relevant Code or Code Sandbox**
Code I use to destory:
`ngOnDestroy() {
    const tb = (window as any).tb;
    this.sub.unsubscribe();
    tb.dispose();
  }`

Screenshots of error
![image](https://user-images.githubusercontent.com/51290462/143456887-feafb728-ed67-4a37-82ce-f66a97b97fb4.png)

Other notes
I realized that doing tb.dispose does not fully dispose of everything it needs, a couple of stuff still remains on window.tb as well as in the tb.memory().  Would it be possible to put the tb onto a non global variable?

Any help appreciated!
Thanks

**Comment by jscastro76** [comment]
Thanks for reporting this issue.
The error stack you shared seems like `tb.update` is being called anywhere in your code after the dispose, and that shouldn’t happen. I have different versions of Threebox in different production environments and I have not experienced this issue disposing Threebox.

[Example number 15](https://github.com/jscastro76/threebox/tree/master/examples) shows the use `tb.dispose`

```js
$('#dispose').on('click', function () {
			const result = window.tb.dispose();
			console.log(result);
			window.tb = {};
		});

```

if the issue reproduces in this example I’ll open a bug. If not, it’s probably due to an issue in your code so it would be better if you can share a minimum reproducible example on your preferred code sandbox that I can take a look at

regarding the objects in memory, Mapbox and specially Three.js cannot free the memory instantaneously. This is inherent to their implementation, you’ll find tens of articles written about how to dispose three.js objects, I followed some of them to implement dispose, but there could be a better way to do it. Other option if Threebox dispose implementation doesn’t fit your needs you can reimplement in your own method

**Comment by Philip2809** [comment]
Hi again!

I will try to make a reproducible sample but it's a pretty big project, but I will try to do something. When I call dispose, the update should not be called until the threebox is reinitialized, but you mean that it would call update between the initialization and the threebox being ready? I will also go tough my code to try to find exactly what part calls this update method.

Also as I asked before; there is no way to store threebox on a non global variable?
