### ISSUE TITLE
How to get the MVP matrix of the camera in the mapbox separately

### ISSUE THREAD

**Issue by famousgeneral306** [jscastro76/threebox#304]
I am implementing the video fusion function and need to get the MVP matrix of the camera in the mapbox, but it seems that this.camera.projectionMatrix in the mapbox contains more than just projection information.

**Comment by jscastro76** [comment]
They way the projection matrix is being build is due to the synchronization with Mapbox camera, it took quite a lot of work and reverse engineering of the Mapbox code to get a pixel-perfect fit between both cameras.

Check out this code on [CameraSync code](https://github.com/jscastro76/threebox/blob/9e72e5d4d4498450e1cafb6d687ba2b8e5426a47/src/camera/CameraSync.js#L108), up to this point all the variables to calculate it are decomposed, so probably you can calculate it by yourself with those.
