### ISSUE TITLE
Question about model positioning when importing from Blender

### ISSUE THREAD

**Issue by PSP789456** [jscastro76/threebox#308]
**Threebox version**: 2.2.5

### Question
Hello! I am using threebox to display 3D objects on the map and have a question. Some time ago I used Three.js for this purpose and when I used it, the process of adding models was next: One person from the group created and positioned model (Blender+OSM-Addon I guess) and then I just imported .glb model file into our project.
Code looked like this: https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/
The model was posioned well, matched blender coords. But in threebox, while I am trying importing the model, it doesn't match blender coords at all. I am using code like in this example to import models into threebox: https://github.com/jscastro76/threebox/blob/master/examples/06-object3d.html
Is there a way to configure threebox to match blender coords?

**Comment by jscastro76** [comment]
All the models in Threebox are adjusted and self centered to be able to define an anchor and pivoting point without considering positional gaps or extra spaces, so position can be extremely precise. This is by design, so to your question, the answer is no. But if you share what’s the issue you’re facing in an minimum reproducible example I could take a look to it and recommend you a workaround
