### ISSUE TITLE
Changing Scale On Existing 3D Object Not Working

### ISSUE THREAD

**Issue by nutthapol-jr** [jscastro76/threebox#312]
I use input element for handle 3D object scale and use obj.set({scale: number}) still nothing

1. click on 3D object
2. change scale on input element
3. See error

I expect the scale to be controlled.

Focus on function  onChangeScale [Sandbox](https://codesandbox.io/s/react-threebox-handle-scale-3d-object-o4tte)

**Comment by jscastro76** [comment]
Thanks for reporting!
Several things, first of all you are not using directly Mapbox but maplibre-gl, that is not supported, indeed I receive continuous warnings in you code sandbox due to images not loaded and it ends in a context lost.
![image](https://user-images.githubusercontent.com/38470852/147759122-83cb48d2-dbf5-418d-b5af-b5ab84baeb9d.jpg)
I’d appreciate clarity when reporting a bug.
Changing an object scale needs to consider many factors (scene or meters based, fixed zoom, container groups for …). For that it was created the method `obj.setScale` as defined in the documentation and not `obj._setObject` which is internal as indicated by the underscore
As your code sandbox lost the context due to the lost images I cannot verify it works, but is the method that allows instantaneous change in size on fixed zoom examples.

**Comment by nutthapol-jr** [comment]
Are you have example for change an object scale?
Thank you for response.

**Comment by jscastro76** [comment]
[example 19](https://github.com/jscastro76/threebox/blob/master/examples/19-fixedzoom.html) shows how to change the scale of an object based on the zoom of the map using the method `obj.setObjectScale` for fixed zoom objects. 
You can transform it easily into an example that uses the scale of the object for non-fixed zoom objects using the method `obj.setScale` instead
