### ISSUE TITLE
GLTF objects not visible if setCoords() not called

### ISSUE THREAD

**Issue by federicofernandez** [jscastro76/threebox#332]
I'm loading a GLTF file that contains around 100 models, that represent buildings in an area of Denver. As they are buildings, they should be appropriate placed to the corresponding parcels.

If I try to just load them, and add to the scene, they don't appear. If I force the position with a `setCoords` call, they appear but with a wrong scale, what makes them not to coincide with the parcels. 

I tried both with `meters` and `scene` units. In the case of `scene` the buildings are shown at a very large scale. With `meters` they look better, but still I need to scale them around at `.75` to more or less look like they should.

This is the relevant code:

```
var options = {
  obj: 'buildings.gltf',
  type: 'gltf',
  units: 'meters',
  rotation: { x: 0, y: 0, z: 180 },
  anchor: 'center'
}

tb.loadObj(options, function (model) {
  tb.add(model);
});
```

The models are in EPSG 3857, and the coordinates look like:

<img width="188" alt="Screen Shot 2022-02-18 at 16 37 39" src="https://user-images.githubusercontent.com/1865197/154753462-e76bc164-456b-43e0-be1c-c464f68e95ac.png">

I can provide the GLTF model and my code if needed, and also screenshots of the different alternatives.

I'm using MapBox GL v 2.2.0, with ThreeBox v 2.2.6.

Let me know if I can provide more details. Thanks!

**Comment by jscastro76** [comment]
It’s not a bug, it’s by design, unless you position the object through serCoords the object cannot be represented because it cannot be placed.
Regarding the placement, you’re using an anchor center, try with anchor:auto, but the scale depends on you, consider in Mercator perspective by Mapbox design a meter is different at different latitude and that’s calculated on serCoords, so your if model is in strict meters probably that is only perfect at Ecuator line 0,0 coords. You can easily activate dragging and adjust your model position with precision.
You’ll need to play with scale param to fit it in the perfect scale for Denver latitude

**Comment by federicofernandez** [comment]
> You’ll need to play with scale param to fit it in the perfect scale for Denver latitude

Is there a way to deactivate that scaling? (i.e. just draw the size the 3D object has?)

Thanks!

**Comment by jscastro76** [comment]
`scale: 1` in your loading params
