### ISSUE TITLE
Cloning in Box3 necessary?

### ISSUE THREAD

**Issue by janhaa** [jscastro76/threebox#333]
**Threebox version**: 2.2.6

### Question

Hi @jscastro76,
I am trying to work with quite some large objects (> 10 MB) and getting huge slowdowns on hovering:
![image](https://user-images.githubusercontent.com/1587235/157870781-fdc40ed4-732b-4487-ac99-e861874933ac.png)
Obviously it's due to cloning the object down in the stack. 
Is cloning really necessary here? https://github.com/jscastro76/threebox/blob/84ecddbcd312b74ff1b609cd4e5c1cb42effa7fd/src/objects/objects.js#L691

If you can give me some broad pointers I can happily assist with a pull request (sadly I don't have the time right now to dig deep into the logic behind it).

Thank you for your work!

**Comment by jscastro76** [comment]
The bounding box of an object must be recalculated in real time on hover as the object could have changed or rescaled by threebox, otherwise bounding box and position of its label would be wrong, so long story short, yes, it is needed.

But you can avoid creating a bounding box or a tooltip using `bbox: false` and `tooltip: false` so that code won't be executed
