### ISSUE TITLE
Collision detection is not working for custom model loaded using `tb.loadObj`

### ISSUE THREAD

**Issue by jianbocui** [jscastro76/threebox#338]
**Threebox version**:
Version 2.2.6
### Question

Hi There,

In the game example, I want to detect if the car intercepts with a loaded model either in the same layer as the truck or on a different layer using `truck.addEventListener('ObjectChanged', onObjectChanged, false);`, here is my [example code ](https://codesandbox.io/s/nostalgic-browser-b2m9ep?file=/index.html), but the `onObjectChanged` doesn't detect anything when it intercept with the object

![Screen Shot 2022-03-18 at 5 14 06 pm](https://user-images.githubusercontent.com/96053057/158954251-39c1d58f-29ab-45ec-a764-1ac9d949cf36.png)
![Screen Shot 2022-03-18 at 5 13 40 pm](https://user-images.githubusercontent.com/96053057/158954258-59877bd2-a478-454d-9d3e-11681c592167.png)

**Comment by jscastro76** [comment]
You're mixing concepts, first, the object is not changing when it moves neither if it intercepts any other object models. So the event handler you're adding is not being fired. Second, the fill-extrusions created by Mapbox are not "visible" for Three.js raycaster, so you won't be able to detect that collisions because both objects are different 3D elements created by 2 different 3D frameworks.
If what you want is to detect collisions between different objects, I recommend you to first check [how detect collisions should be done ](https://stackoverflow.com/questions/11473755/how-to-detect-collision-in-three-js) in three.js without mapbox and threebox, and then implement it in your scenario.
