### ISSUE TITLE
vue and threebox,map not defined

### ISSUE THREAD

**Issue by luojiandan** [jscastro76/threebox#54]
![image](https://user-images.githubusercontent.com/5663556/96328302-281a6000-1074-11eb-824e-be26ffddb7b5.png)
![image](https://user-images.githubusercontent.com/5663556/96328298-1cc73480-1074-11eb-8302-7225c425c090.png)
![image](https://user-images.githubusercontent.com/5663556/96328300-22247f00-1074-11eb-87c4-30d26b8b426a.png)

**Comment by jscastro76** [comment]
This works since the beginning as it comes from the original Threebox, but it´s definitely a bad practice to use a global variable in internal methods, that´s why it could crash unexpectedly if the mapbox object is not called map. 
Requires a bit of analysis, not as easy as it seems as objects prototype is widely used no cannot use the internal map instance.

**Comment by luojiandan** [comment]
@jscastro76 thanks for your replay:)，yes,It has a global varable "map" in it,Let me read the code more carefully again.

**Comment by jscastro76** [comment]
@luojiandan working on this, it´s resolved for the next version

**Comment by jscastro76** [comment]
@luojiandan please test this in v2.0.7 release
